### ISSUE TITLE
Could we have a version of `set` that assumes that the key don't exists?

### ISSUE THREAD

**Issue by meditans** [turingjump/bookkeeper#18]
This probably would help with the issue delineated in #16.

**Comment by meditans** [comment]
To be fair, I wonder if, now that that issue is solved, this wouldn't complicate the api without other benefits. Do you envision other use cases for this?

**Comment by jkarni** [comment]
We'd also probably then need one that assumes they _do_ exist. I think the takeaway from #16 is that documentation about how to do this ought to be better (and perhaps there ought to be more helper constraints). Closing.
