### ISSUE TITLE
Generic-based conversion to/from ordinary Haskell records

### ISSUE THREAD

**Issue by fizruk** [turingjump/bookkeeper#22]
All the necessary info is already there with GHC 8's new Generic's metadata.

**Comment by jkarni** [comment]
Yeah! The way I was thinking of this was by converting to/from `generics-sop`'s [NP](https://hackage.haskell.org/package/generics-sop-0.2.2.0/docs/Generics-SOP.html#t:NP), which should be pretty easy.

**Comment by jkarni** [comment]
Done in #22

**Comment by xnmp** [comment]
@jkarni I see that there's a `fromRecord` function, how can we convert a Book to a record? More specifically I want to be able to get the following boilerplate for free:

```haskell
type ColProject = Book '[ "project_id" :=> Column PID
                     , "user_id" :=> Column UID 
                     , "timestamp" :=> Column LocalTime]

qProject :: Query ColProject
qProject = pure $ emptyBook 
    & #project_id =: baseCol' "project_id" "projects"
    & #user_id =: baseCol' "user_id" "projects"
    & #timestamp =: baseCol' "timestamp" "projects"
```

I also want to retrieve all of the values from a book without manually typing in all the field names.
